PREFIX analysis:	<http://imce.jpl.nasa.gov/foundation/analysis#>
PREFIX constraint:	<http://opencaesar.io/firesat-telecom/telecom-supplier/vocabulary/constraint#>

SELECT ?child ?parent

WHERE {
	[
		a constraint:CausalConstraint;
		analysis:explains ?parent;
		analysis:analyzes ?child;
	]
}